project:
  type: website

website:
  title: "include-relative-paths"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

quarto-required-version: ">=1.2.67"


